# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Setup Environment'

  - script: |
      npm install npx
      npm install
      npx ng build --prod
      npx ng build api --prod

    displayName: 'Build'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'node_modules'
      Contents: '**'
      TargetFolder: 'dist/apps/api/node_modules'
    displayName: 'Copy node_modules for API'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/apps/regression-poc'
      ArtifactName: 'web-app'
      publishLocation: 'Container'
    displayName: 'Publish Web Artifacts'

  - task: PublishBuildArtifacts@1

    inputs:
      PathtoPublish: 'dist/apps/api'
      ArtifactName: 'api'
      publishLocation: 'Container'
    displayName: 'Publish API Artifacts'

